repos:
  - repo: https://github.com/mattgodbolt/beebasm-fmt
    rev: v0.1.1
    hooks:
      - id: beebasm-fmt
  - repo: local
    hooks:
      - id: check-rom
        name: check ROM matches original
        entry: ./check.sh
        language: script
        files: '\.asm$'
        pass_filenames: false
      - id: tests
        name: run tests
        entry: npm test
        language: system
        pass_filenames: false
        always_run: true
